// <auto-generated />
using System;
using GACWareHousingApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GACWareHousingApi.Migrations
{
    [DbContext(typeof(GACWareHouseContext))]
    [Migration("20200915204311_GACWareHousingApi.DBContext.GACWareHouseContextSeed")]
    partial class GACWareHousingApiDBContextGACWareHouseContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GACWareHousingApi.Models.Customer", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("CustomerCode");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerCode = "C000001",
                            Address = "UAE",
                            CompanyCode = "GAC",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 55, DateTimeKind.Local).AddTicks(8460),
                            Email = "customerA@gmail.com",
                            FirstName = "Customer A",
                            Id = 0L,
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 58, DateTimeKind.Local).AddTicks(8301),
                            PhoneNumber = "919676000101"
                        },
                        new
                        {
                            CustomerCode = "C000002",
                            Address = "UAE",
                            CompanyCode = "GAC",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 59, DateTimeKind.Local).AddTicks(346),
                            Email = "customerB@gmail.com",
                            FirstName = "Customer B",
                            Id = 0L,
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 59, DateTimeKind.Local).AddTicks(364),
                            PhoneNumber = "919676000102"
                        });
                });

            modelBuilder.Entity("GACWareHousingApi.Models.Manfacturer", b =>
                {
                    b.Property<string>("ManfacturerCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ManfacturerCode");

                    b.ToTable("Manfacturers");

                    b.HasData(
                        new
                        {
                            ManfacturerCode = "M000001",
                            Address = "UAE",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 62, DateTimeKind.Local).AddTicks(7581),
                            Email = "manfacturerA@gmail.com",
                            FirstName = "Manfacturer A",
                            Id = 0L,
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 62, DateTimeKind.Local).AddTicks(7627),
                            PhoneNumber = "919676000101",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("GACWareHousingApi.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManfacturerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProductCode");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductCode = "P000001",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3308),
                            Dimensions = "50 X 20 X 100",
                            Id = 0L,
                            IsDeleted = false,
                            ManfacturerCode = "M000001",
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3325),
                            Price = 25.5f,
                            ProductName = "Product A",
                            UOM = "PC"
                        },
                        new
                        {
                            ProductCode = "P000002",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3511),
                            Dimensions = "50 X 20 X 90",
                            Id = 0L,
                            IsDeleted = false,
                            ManfacturerCode = "M000001",
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3516),
                            Price = 30.5f,
                            ProductName = "Product B",
                            UOM = "PC"
                        },
                        new
                        {
                            ProductCode = "P000003",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3524),
                            Dimensions = "50 X 20 X 70",
                            Id = 0L,
                            IsDeleted = false,
                            ManfacturerCode = "M000001",
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 9, 16, 2, 13, 6, 63, DateTimeKind.Local).AddTicks(3527),
                            Price = 35.5f,
                            ProductName = "Product C",
                            UOM = "PC"
                        });
                });

            modelBuilder.Entity("GACWareHousingApi.Models.SalesOrder", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderCode");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("GACWareHousingApi.Models.SalesOrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalesOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
